name: Build and deploy AtomPacker

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install PyPA's build
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: Build distribution archives
        run: |
          python -m build --wheel --sdist .

      - name: Upload distribution archives
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./dist/*.whl
            ./dist/*.tar.gz

  test-on-different-os:
    name: Test on different on ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    needs: [build]
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ./dist

      - name: Test sdist on ${{ matrix.os }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install ./dist/atompacker-${{ github.event.release.tag_name }}.tar.gz
          python -c 'import AtomPacker; print(AtomPacker.__version__)'
          pytest tests --import-mode=importlib --verbose
          
      - name: Test wheel on ${{ matrix.os }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install ./dist/AtomPacker-${{ github.event.release.tag_name }}-py3-none-any.whl
          python -c 'import AtomPacker; print(AtomPacker.__version__)'
          pytest tests --import-mode=importlib --verbose

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [test-on-different-os]
    environment:
      name: pypi
      url: https://pypi.org/project/AtomPacker
    permissions:
      id-token: write

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ./dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
