name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python --version
          chmod +x build-packmol.sh
          bash build-packmol.sh
          python -m pip install --upgrade pip
          pip install pytest
          pip install .

      - name: Test with pytest
        run: |
          pytest --verbose
